[build]
  # Ин фармон ба Netlify мегӯяд, ки кадом папкаро ҳамчун вебсайти шумо нашр кунад.
  # Агар файли index.html-и шумо дар реша бошад, инро холӣ гузоред ё "." гузоред.
  publish = "." 

[functions]
  # Ин ба Netlify нишон медиҳад, ки функсияҳои серверии шумо дар куҷоянд.
  directory = "netlify/functions/"
